events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    upstream users_service    { server users:8000; }
    upstream products_service { server products:8000; }
    upstream orders_service   { server orders:8000; }

    server {
        listen 80;

        location /api/users/ {
            proxy_pass http://users_service/;
            proxy_set_header Host $host;
        }

        location /api/products/ {
            proxy_pass http://products_service/;
            proxy_set_header Host $host;
        }

        location /api/orders/ {
            proxy_pass http://orders_service/;
            proxy_set_header Host $host;
        }

        location /health {
            return 200 "gateway ok\n";
            add_header Content-Type text/plain;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}